name: "Now That The Candy's Gone"
favicon: null
layout_spectrum: 0.9698750581592321
typography_spectrum: 0.469719051849097
title: How I Learn About Life Success
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#969696'
    - '#b3b3b3'
    - '#d0d0d0'
    - '#273a59'
  brandStrength: 0.3125
  lightness: 0.656258437782526
  saturation: 0.7413086544256657
  rhythmicContrast: 0.0033861841075122356
purpose: []
