name: "Now That The Candy's Gone"
favicon: null
layout_spectrum: 0.9698750581592321
typography_spectrum: 0.469719051849097
title: How I Learn About Life Success
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3050782000645995
  lightness: 0.656258437782526
  saturation: 0.7413086544256657
  rhythmicContrast: 0.0033861841075122356
purpose: []
